//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class veritass_savinaEntities : DbContext
{
    public veritass_savinaEntities()
        : base("name=veritass_savinaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tb_About> tb_About { get; set; }
    public virtual DbSet<tb_Access> tb_Access { get; set; }
    public virtual DbSet<tb_ContactUs> tb_ContactUs { get; set; }
    public virtual DbSet<tb_Counteronline> tb_Counteronline { get; set; }
    public virtual DbSet<tb_Customer> tb_Customer { get; set; }
    public virtual DbSet<tb_LocalAccount> tb_LocalAccount { get; set; }
    public virtual DbSet<tb_Permission> tb_Permission { get; set; }
    public virtual DbSet<tb_promotion> tb_promotion { get; set; }
    public virtual DbSet<tb_SiteMap> tb_SiteMap { get; set; }
    public virtual DbSet<tb_WishList> tb_WishList { get; set; }
    public virtual DbSet<tb_CategoryMain> tb_CategoryMain { get; set; }
    public virtual DbSet<tb_CategorySub1> tb_CategorySub1 { get; set; }
    public virtual DbSet<tb_Order> tb_Order { get; set; }
    public virtual DbSet<Country> Countries { get; set; }
    public virtual DbSet<District> Districts { get; set; }
    public virtual DbSet<Province> Provinces { get; set; }
    public virtual DbSet<tb_CategorySub2> tb_CategorySub2 { get; set; }
    public virtual DbSet<tb_CategorySub3> tb_CategorySub3 { get; set; }
    public virtual DbSet<Ward> Wards { get; set; }
    public virtual DbSet<tb_Product> tb_Product { get; set; }
}
